# Generated by Django 5.2.6 on 2025-09-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug категории")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="products_ca_slug_da4386_idx"),
                    models.Index(fields=["order"], name="products_ca_order_ac6215_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("sku", models.CharField(blank=True, default="", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("old_proce", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="RUB", max_length=3)),
                ("in_stock", models.BooleanField(default=True)),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("new", "New"),
                            ("sale", "Sale"),
                            ("featired", "Featured"),
                        ],
                        db_index=True,
                        default="",
                        max_length=10,
                    ),
                ),
                ("rating_abg", models.FloatField(default=0.0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/%Y/%m/", verbose_name="Изображение товара"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_images",
                        to="products.product",
                        verbose_name="Карточка товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["badge"], name="products_pr_badge_39e7e2_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product"], name="products_pr_product_3d7874_idx"
            ),
        ),
    ]
