# Generated by Django 5.2.6 on 2025-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, verbose_name="Основное изображение"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["is_primary", "sort_order"],
                name="products_pr_is_prim_900698_idx",
            ),
        ),
    ]
