# Generated by Django 5.2.6 on 2025-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage_is_primary_productimage_sort_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("new", "New"),
                    ("sale", "Sale"),
                    ("featired", "Featured"),
                ],
                db_index=True,
                default="",
                max_length=10,
                verbose_name="Бренд",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="RUB", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="В наличии"),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_proce",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Старая цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating_abg",
            field=models.FloatField(default=0.0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество оценок"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество на складе"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
